# ===================== Install Apps =====================
# This block installs the some basic apps, such as browser, 
# terminal, editor, file manager, etc.

version = 1
description = "Apps"

[[packages]]
names = [
    "brightnessctl",
    "firefox",
    "nano",
    "neovim",
    "fd",
    "ripgrep",
    "fzf",
    "kitty",
    "networkmanager",
    "yazi",
    "swayimg",
    "bat",
    "eza",
    "ripgrep-all"
]

[[symlink]]
source = "dotfiles/yazi"
target = "~/.config/yazi"

[[shell]]
script = "xdg-settings set default-web-browser firefox.desktop"

[[service]]
name = "NetworkManager.service"
