# ========== Install Display Manager (SDDM) ==========
# Display Manager is responsible for displaying the desktop environment.

version = 1
description = "Display manager (SDDM)"

[[packages]]
names = ["sddm"]

[[service]]
name = "sddm.service"
