# ========== Install Display Manager (greetd) ==========
# Display Manager is responsible for displaying the desktop environment.
# I use greetd + regreet for a minimal display manager.

version = 1
description = "Display manager (greetd)"

[[packages]]
names = ["greetd", "greetd-regreet"]

[[symlink]]
source = "dotfiles/greetd"
target = "/etc/greetd"

[[service]]
name = "greetd.service"
