# ======== Install tlp ========

version = 1
description = "tlp"

[[packages]]
names = [
  "tlp",
  "tlp-ui",
  "tlp-pd"
]

[[service]]
name = "tlp.service"

[[service]]
name = "tlp-pd.service"

[[symlink]]
source = "dotfiles/tlp/tlp.conf"
target = "/etc/tlp.conf"
