version = 1
description = "Browser"

[[commands]]
kind = "package"
backend = "yay"
name = "thorium-browser-bin"

[[commands]]
kind = "shell"
script = """
xdg-settings set default-web-browser thorium-browser.desktop
"""


